

SELECT 
    CLIENT_NAME,
    ORDER_AT AS ORDER_AT_TS,
    ORDER_ID,
    PAYMENT_INFO,
    PAYMENT_METHOD,
    PHONE,
    SESSION_ID,
    SHIPPING_ADDRESS,
    SHIPPING_COST,
    (REPLACE(SHIPPING_COST, 'USD', '')) AS CLEAN_SHIPPING_COST,
    STATE,
    TAX_RATE,
    _FIVETRAN_DELETED,
    _FIVETRAN_ID,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{source('web_schema', 'orders')}}

