SELECT 
    CLIENT_ID AS CLIENT_ID,
    CAST(CLIENT_ID AS VARCHAR) AS CLIENT_ID_AS_STRING,
    IP,
    OS,
    SESSION_AT AS SESSION_AT_TS,
    SESSION_ID,
    _FIVETRAN_DELETED,
    _FIVETRAN_ID,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{source('web_schema', 'sessions')}}
