SELECT _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    DATE,
    EXPENSE_TYPE,
    TRY_TO_NUMBER(REPLACE(EXPENSE_AMOUNT, '$', '')) AS CLEAN_EXPENSE_AMOUNT

FROM {{source('google_drive', 'expense')}}

