version: 2

sources:
  - name: google_drive
    database: LOAD
    schema: google_drive
    tables:
      - name: expense
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: hr_joins
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: hr_quits
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: returns
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

  - name: web_schema
    database: LOAD
    schema: snowflake_columbia_web_schema
    tables:
      - name: item_views 
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: orders
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: page_views
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced

      - name: sessions
        freshness:
          warn_after:
            count: 1
            period: day
          error_after: 
            count: 3
            period: day
        loaded_at_field: _fivetran_synced
    